{{- if .Values.postgresqlExporter.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secure-haven-vault.fullname" . }}-exporter
  labels:
    {{- include "secure-haven-vault.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
        {{- include "secure-haven-vault.exporter.selectorLabels" . | nindent 8 }}
        {{- with .Values.postgresqlExporter.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  template:
    metadata:
      labels:
        {{- include "secure-haven-vault.exporter.selectorLabels" . | nindent 8 }}
        {{- with .Values.postgresqlExporter.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "secure-haven-vault.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.postgresqlExporter.podSecurityContext | nindent 8 }}
      {{- with .Values.postgresqlExporter.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres-exporter
          image: "{{ .Values.postgresqlExporter.image.repository }}:{{ .Values.postgresqlExporter.image.tag }}"
          imagePullPolicy: {{ .Values.postgresqlExporter.image.pullPolicy }}
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "secure-haven-vault.appSecretName" . }}-exporter
                  key: DATA_SOURCE_NAME
            - name: PG_EXPORTER_EXTEND_QUERY_PATH
              value: /etc/postgres_exporter/queries.yaml
          volumeMounts:
            - name: queries
              mountPath: /etc/postgres_exporter
      volumes:
        - name: queries
          configMap:
            name: postgres-custom-queries
{{- end }}
