{{- if and .Values.postgresqlExporter.enabled (not .Values.config.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-haven-vault.appSecretName" . }}-exporter
  labels:
    {{- include "secure-haven-vault.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresqlExporter.datasource.urlKey }}: {{ required "postgresqlExporter.datasource.urlKey is required when postgresqlExporter.datasource.existingSecret is empty" .Values.postgresqlExporter.datasource.url | quote }}
{{- end }}
