{{- if .Values.postgresqlExporter.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secure-haven-vault.fullname" . }}-exporter
  labels:
    {{- include "secure-haven-vault.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "secure-haven-vault.exporter.selectorLabels" . | nindent 8 }}
    {{- with .Values.postgresqlExporter.podLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
  ports:
    - port: 9187
      targetPort: 9187
{{- end }}
