{{ $exporter := index .Values "prometheus-postgres-exporter" }}
{{- if $exporter.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-custom-queries
data:
  queries.yaml: |
    secret_expiry:
      query: |
        SELECT
          name,
          EXTRACT(
            EPOCH FROM (expires_at - now())
          ) / 86400 AS days_remaining
        FROM secrets
        WHERE expires_at > now()
      metrics:
        - name:
            usage: LABEL
            description: Secret name
        - days_remaining:
            usage: GAUGE
            description: Days before expiration
{{- end }}
