{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-haven-vault.appSecretName" . }}
  labels:
    {{- include "secure-haven-vault.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.masterEncryptionKeyKey }}: {{ required "config.masterEncryptionKey is required when config.existingSecret is empty" .Values.config.masterEncryptionKey | quote }}
  {{ .Values.config.databaseUrlKey }}: {{- if .Values.postgresql.enabled }}
    {{ printf "postgres://%s:%s@%s:5432/%s" .Values.postgresql.auth.username (required "postgresql.auth.password is required when bundled PostgreSQL is enabled without an existing secret" .Values.postgresql.auth.password) (include "secure-haven-vault.postgresqlName" .) .Values.postgresql.auth.database | quote }}
    {{- else }}
    {{ required "externalDatabase.url is required when postgresql.enabled=false" .Values.externalDatabase.url | quote }}
    {{- end }}
{{- end }}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-haven-vault.postgresqlSecretName" . }}
  labels:
    {{- include "secure-haven-vault.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.auth.passwordKey }}: {{ required "postgresql.auth.password is required when postgresql.auth.existingSecret is empty" .Values.postgresql.auth.password | quote }}
{{- end }}
