/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiPublicOidcCallbackRouteImport } from './routes/api/public/oidc/callback'
import { Route as ApiPublicOidcStartRouteImport } from './routes/api/public/oidc/start'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicOidcCallbackRoute = ApiPublicOidcCallbackRouteImport.update({
  id: '/api/public/oidc/callback',
  path: '/api/public/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOidcStartRoute = ApiPublicOidcStartRouteImport.update({
  id: '/api/public/oidc/start',
  path: '/api/public/oidc/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/api/public/oidc/callback': typeof ApiPublicOidcCallbackRoute
  '/api/public/oidc/start': typeof ApiPublicOidcStartRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/oidc/callback': typeof ApiPublicOidcCallbackRoute
  '/api/public/oidc/start': typeof ApiPublicOidcStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/oidc/callback': typeof ApiPublicOidcCallbackRoute
  '/api/public/oidc/start': typeof ApiPublicOidcStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/api/public/oidc/callback' | '/api/public/oidc/start'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/' | '/api/public/oidc/callback' | '/api/public/oidc/start'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/api/public/oidc/callback'
    | '/api/public/oidc/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicOidcCallbackRoute: typeof ApiPublicOidcCallbackRoute
  ApiPublicOidcStartRoute: typeof ApiPublicOidcStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/oidc/callback': {
      id: '/api/public/oidc/callback'
      path: '/api/public/oidc/callback'
      fullPath: '/api/public/oidc/callback'
      preLoaderRoute: typeof ApiPublicOidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oidc/start': {
      id: '/api/public/oidc/start'
      path: '/api/public/oidc/start'
      fullPath: '/api/public/oidc/start'
      preLoaderRoute: typeof ApiPublicOidcStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicOidcCallbackRoute: ApiPublicOidcCallbackRoute,
  ApiPublicOidcStartRoute: ApiPublicOidcStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
